[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name="aspn23_lcm_conversions"
version="1.0.1"
description="A set of functions to convert between ASPN-Python and ASPN-LCM"
dependencies=[
    "aspn23>=1.0.0, <2.0.0",
    "aspn23_lcm>=1.0.0, <2.0.0",
    "numpy"
]
requires-python = ">= 3.5"
license = 'Apache-2.0'
license-files = ['LICENSE']
readme = 'README.md'
