name: Generate

on: [push, pull_request]

jobs:
    Generate:
        runs-on: ubuntu-24.04
        steps:
        - uses: actions/checkout@v4

        - name: Set up firehose docker container
          uses: ./.github/actions/setup
          with:
            tag: firehose
            dockerfile: Dockerfile

        - name: Set up ROS jazzy docker container
          uses: ./.github/actions/setup
          with:
            tag: firehose-jazzy
            dockerfile: Dockerfile.ros
            ros_distro: jazzy

        - name: Set up ROS humble docker container
          uses: ./.github/actions/setup
          with:
            tag: firehose-humble
            dockerfile: Dockerfile.ros
            ros_distro: humble

        - name: Generate
          run: |
              set -xe
              docker run --rm -dit -v $(pwd):/firehose -v $(pwd)/.ccache:/home/docker/.ccache --name firehose firehose bash
              docker exec firehose uv sync
              docker exec firehose ./generate.py --all

        - name: Make output into a git repo
          run: |
                eval `ssh-agent -s`
                ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY_WRITE }}'
                git clone git@github.com:stratus-community/stratus-aspn-generated.git
                cd stratus-aspn-generated
                git checkout $GITHUB_REF_NAME || git checkout -b $GITHUB_REF_NAME
                cp -r .git ../output/

        - name: Build ASPN-ROS Ubuntu packages
          run: |
              cd output
              # Build generated ros_devel/ stuff in ROS containers only if aspn-ros/ has changed
              if [ ! -n "$(git status ./aspn-ros --porcelain)" ]; then
                echo "No ROS changes to push. Skipping rebuild of ROS Ubuntu dev packages."
              else
                docker run --rm -v $(pwd):/output firehose-humble
                docker run --rm -v $(pwd):/output firehose-jazzy
                git add ./ros_devel  # Stage ros_devel/ changes
              fi

        - name: Commit changes
          run: |
                # Harvest commit description before moving on
                export COMMIT_DESCRIPTION=$(git log -1 --pretty=%B)
                cd output
                if [ ! -n "$(git status --porcelain . -- ':!./ros_devel')" ]; then
                    echo "No changes to commit"
                else
                    # Commit code changes before meson setup build and tests
                    git add . ':!./ros_devel'  # Exclude ros_devel/ (let it be handled above)
                    GIT_COMMITTER_NAME="$(git log -1 --pretty=%cn)" \
                        GIT_COMMITTER_EMAIL="$(git log -1 --pretty=%ce)" \
                        GIT_AUTHOR_NAME="$(git log -1 --pretty=%an)" \
                        GIT_AUTHOR_EMAIL="$(git log -1 --pretty=%ae)" \
                        git commit -m "Firehose commit ${GITHUB_SHA} code generation" -m "$COMMIT_DESCRIPTION"
                fi

        - name: Test static typing of output
          run: |
                # Run mypy
                docker exec --workdir /firehose/output/aspn-py firehose mypy . --strict

        - name: Fix ownership of cache
          run: sudo chown -R $USER:$USER .ccache

        - name: Restore ccache cache before building
          uses: actions/cache/restore@v4
          with:
            path: ${{github.workspace}}/.ccache
            key: ccache-${{ github.run_id }}
            restore-keys: ccache-

        - name: Test building output
          run: |
                # Build and run any tests
                docker exec --workdir /firehose/output firehose meson setup build -Dwerror=true
                docker exec --workdir /firehose/output firehose ninja -C build test

        - name: Save ccache cache
          uses: actions/cache/save@v4
          with:
            path: ${{github.workspace}}/.ccache
            key: ccache-${{ github.run_id }}

        - name: Deploy results
          run: |
                eval `ssh-agent -s`
                ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY_WRITE }}'
                cd output
                git push origin $GITHUB_REF_NAME
